server :
  servlet:
      context-path: /cliente-pet/api
      

  spring:
    h2:
      console:
        enable= true
        path=/h2
 
  datasource: 
       url=jdbc:h2:file:/home/wolmir/dbh2teset
          username=root
           password= root
            driver-class-name=org.h2.Driver
  jpa:
    hibernate:
      ddl-auto= update
  