server :
  servlet:
      context-path: /cliente-pet/api
      

  spring:
    h2:
      console:
        enable: true
        path: /h2-console
 
  datasource: 
         url: jdbc:h2:men:demodb
         username: sa
         password: 1234
         driverClassName: org.h2.Driver

  